# Generated by Django 5.0.4 on 2025-01-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_options_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
    ]
