# Generated by Django 5.0.4 on 2025-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
