# Generated by Django 5.0.4 on 2025-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_post_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='translations',
        ),
        migrations.AddField(
            model_name='recipe',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
