# Generated by Django 5.2.1 on 2025-07-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_post_translations_recipe_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='average_rating',
        ),
    ]
