# Generated by Django 5.2.1 on 2025-07-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_post_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
