databases:
  - name: gourmetlink-db
    databaseName: gourmetlink
    user: postgres
    password: chaosdevil

services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn gourmet.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: +^+hgh(z=)vrs6^&39^@+!y&sljw!9&3mwv@!j1qpw%zl7vtph
      - key: DATABASE_URL
        value: postgres://postgres:chaosdevil@dpg-cuodl1aj1k6c73987230-a:5432/gourmetlink
        fromDatabase:
          name: gourmetlink-db
          property: connectionString
      # Email settings
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: "teamgourmetlink@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "yffv zrtg vfle jpnx"
      - key: DEFAULT_FROM_EMAIL
        value: "teamgourmetlink@gmail.com"