# Generated by Django 5.2.1 on 2025-07-08 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_mealplanentry_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['end_date'], name='features_me_end_dat_656673_idx'),
        ),
    ]
